name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # --- CÁC THƯ VIỆN CẦN THIẾT ---
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2  # MỚI: Lưu chế độ Dark Mode

  # Xử lý file & ảnh
  device_info_plus: ^10.1.2
  file_picker: ^10.3.8
  pdf: ^3.10.4
  printing: ^5.11.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5

  # UI & Tiện ích
  carousel_slider: ^5.0.0     # Đã nâng cấp để tránh lỗi xung đột
  fl_chart: ^0.66.0
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true